# Generated by Django 3.2 on 2022-10-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0002_alter_well_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='Company',
        ),
    ]
