# Generated by Django 3.2 on 2022-10-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('Available', models.BooleanField(default=True, verbose_name='Available')),
                ('IpAddress', models.CharField(max_length=100, unique=True, verbose_name='Ip Address')),
                ('ControlMode', models.CharField(choices=[('None', 'None'), ('Amperage', 'Amperage'), ('Frequency', 'Frequency')], default='None', max_length=10, verbose_name='Control Mode')),
                ('ControlSetPoint', models.FloatField(blank=True, null=True, verbose_name='Control SetPoint')),
                ('ControlSetPointChokeValve', models.FloatField(blank=True, null=True, verbose_name='SetPoint ChokeValve')),
            ],
        ),
    ]
