# Generated by Django 3.2 on 2022-10-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('well', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='PumpName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='well.well'),
        ),
    ]
