# Generated by Django 3.2 on 2022-10-18 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('overview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('well', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welltest',
            name='PumpName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='well.well'),
        ),
        migrations.AddField(
            model_name='welltest',
            name='UserAuthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='PumpName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='well.well'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='UserAuthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rodpumpdata',
            name='PumpName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='well.well'),
        ),
        migrations.AddField(
            model_name='espevent',
            name='PumpName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='well.well'),
        ),
        migrations.AddField(
            model_name='espdata',
            name='PumpName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='well.well'),
        ),
        migrations.AddField(
            model_name='builduptest',
            name='PumpName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='well.well'),
        ),
        migrations.AddField(
            model_name='builduptest',
            name='UserAuthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
