# Generated by Django 3.2 on 2022-10-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='failures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('DateFailure', models.DateTimeField()),
                ('FailureDiagnosis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Failure Diagnosis')),
                ('PullOut', models.DateTimeField()),
                ('RunLife', models.FloatField(blank=True, null=True, verbose_name='Run Life')),
            ],
            options={
                'verbose_name': 'failures',
                'verbose_name_plural': 'failures',
            },
        ),
        migrations.CreateModel(
            name='kpiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('StopHours', models.FloatField(blank=True, null=True, verbose_name='Stop Hours')),
                ('Deferment', models.FloatField(blank=True, null=True, verbose_name='Deferment')),
                ('RunLife', models.FloatField(blank=True, null=True, verbose_name='Run Life')),
                ('FieldName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field')),
            ],
            options={
                'verbose_name': 'deferment',
                'verbose_name_plural': 'deferment',
            },
        ),
    ]
