# Generated by Django 3.2 on 2022-10-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0001_initial'),
        ('kpi', '0001_initial'),
        ('well', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpidata',
            name='PumpName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_kpi', to='well.well'),
        ),
        migrations.AddField(
            model_name='failures',
            name='FieldName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Field_failures', to='field.field'),
        ),
        migrations.AddField(
            model_name='failures',
            name='PumpName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_failures', to='well.well'),
        ),
    ]
