# Generated by Django 3.2 on 2022-10-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpidata',
            name='FieldName',
        ),
    ]
