# Generated by Django 3.2 on 2022-10-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_remove_kpidata_fieldname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failures',
            name='FieldName',
        ),
    ]
