# Generated by Django 3.2 on 2022-10-19 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options'),
        ('users', '0002_alter_user_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CompanyName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to='company.company'),
        ),
    ]
