# Generated by Django 3.2 on 2022-10-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('FieldName', models.CharField(max_length=100, unique=True, verbose_name='Field Name')),
                ('Company', models.CharField(max_length=100, verbose_name='Company')),
                ('LocationState', models.CharField(max_length=100, verbose_name='Location State')),
                ('LocationCounty', models.CharField(max_length=100, verbose_name='Location County')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
    ]
